### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-dht

### ISSUE THREAD

**Issue by ukjoci** [NorthernMan54/homebridge-dht#36] opened 2019-10-06 20:15 UTC
Hi There!

I have a problem with running or loading dht plugin in Homebridge. Before it worked, but it broguht time to work.
But now, I get this error message and my DHT22 plugin doesn't work with Homebridge and iOS Home Kit.
The DHT22 sensor is good, because in Raspi terminal i can read out the values of temperature and humidity.

Here is the full error message from the terminal:

> ERROR LOADING PLUGIN homebridge-dht:
> [2019-10-6 22:11:04] Error: Cannot find module '/home/pi/homebridge-dht/node_modules/node-dht-sensor/build/Release/node_dht_sensor'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:288:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:515:18)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:759:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:677:27)
>     at Module.require (internal/modules/cjs/loader.js:830:19)
>     at require (internal/modules/cjs/helpers.js:68:18)
>     at Object.<anonymous> (/home/pi/homebridge-dht/index.js:40:14)
>     at Module._compile (internal/modules/cjs/loader.js:936:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
>     at Module.load (internal/modules/cjs/loader.js:790:32)
And here is a picture of it also.

Many-many thanks for your help!
![dht_problem](https://user-images.githubusercontent.com/56235153/66275226-d4810e00-e886-11e9-9c97-56a0f5f6c3df.jpg)

**Comment by NorthernMan54** [comment] 2019-10-06 23:12
This looks like a duplicate of #33 

Can you close this and we can track there

**Closed as completed** 2019-10-07 05:28 UTC
